### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: Missing required properties: onInitError onMissingData

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#109]
**Exception:** 	 io.reactivex.exceptions.OnErrorNotImplementedException: Missing required properties: onInitError onMissingData
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen.lambda$onAttachedToWindow$3(DetailsScreen.java:412)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen$$Lambda$4.accept(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
	at android.view.View.performClick(View.java:6213)
	at android.view.View$PerformClick.run(View.java:23645)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.IllegalStateException: Missing required properties: onInitError onMissingData
	at com.github.ayltai.newspaper.speech.AutoValue_SimpleTextToSpeech$Builder.internalBuild(AutoValue_SimpleTextToSpeech.java:117)
	at com.github.ayltai.newspaper.speech.SimpleTextToSpeech$Builder.build(SimpleTextToSpeech.java:50)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen.textToSpeech(DetailsScreen.java:326)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.onTextToSpeechClick(DetailsPresenter.java:108)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.lambda$onViewAttached$10(DetailsPresenter.java:166)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter$$Lambda$11.accept(Unknown Source)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 15 more

Caused by: 
java.lang.IllegalStateException: Missing required properties: onInitError onMissingData
	at com.github.ayltai.newspaper.speech.AutoValue_SimpleTextToSpeech$Builder.internalBuild(AutoValue_SimpleTextToSpeech.java:117)
	at com.github.ayltai.newspaper.speech.SimpleTextToSpeech$Builder.build(SimpleTextToSpeech.java:50)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen.textToSpeech(DetailsScreen.java:326)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.onTextToSpeechClick(DetailsPresenter.java:108)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.lambda$onViewAttached$10(DetailsPresenter.java:166)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter$$Lambda$11.accept(Unknown Source)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen.lambda$onAttachedToWindow$3(DetailsScreen.java:412)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen$$Lambda$4.accept(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
	at android.view.View.performClick(View.java:6213)
	at android.view.View$PerformClick.run(View.java:23645)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Number:** 	 8

**URL:** 	 https://insta.co/crashes/eM7Q92zy

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-15 06:47:38 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2447.0/3533.0 MB

**Storage:** 	 18.743/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: Radiohead

**Battery:** 	 100, Charging through USB cable

**App Version:** 	 3.2.628-4bb6e1d (20)

**Duration:** 	 42

**User Data:** 	 

**Console Log:**
```
ubscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)

1508050058103  W/System.err(27517): 	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)

1508050058104  W/System.err(27517): 	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)

1508050058104  W/System.err(27517): 	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)

1508050058104  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsScreen.lambda$onAttachedToWindow$3(DetailsScreen.java:412)

1508050058104  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsScreen$$Lambda$4.accept(Unknown Source)

1508050058104  W/System.err(27517): 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)

1508050058104  W/System.err(27517): 	at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)

1508050058104  W/System.err(27517): 	at android.view.View.performClick(View.java:6213)

1508050058104  W/System.err(27517): 	at android.view.View$PerformClick.run(View.java:23645)

1508050058104  W/System.err(27517): 	at android.os.Handler.handleCallback(Handler.java:751)

1508050058104  W/System.err(27517): 	at android.os.Handler.dispatchMessage(Handler.java:95)

1508050058104  W/System.err(27517): 	at android.os.Looper.loop(Looper.java:154)

1508050058104  W/System.err(27517): 	at android.app.ActivityThread.main(ActivityThread.java:6692)

1508050058104  W/System.err(27517): 	at java.lang.reflect.Method.invoke(Native Method)

1508050058104  W/System.err(27517): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)

1508050058105  W/System.err(27517): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

1508050058105  W/System.err(27517): Caused by: java.lang.IllegalStateException: Missing required properties: onInitError onMissingData

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.speech.AutoValue_SimpleTextToSpeech$Builder.internalBuild(AutoValue_SimpleTextToSpeech.java:117)

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.speech.SimpleTextToSpeech$Builder.build(SimpleTextToSpeech.java:50)

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsScreen.textToSpeech(DetailsScreen.java:326)

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.onTextToSpeechClick(DetailsPresenter.java:108)

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.lambda$onViewAttached$10(DetailsPresenter.java:166)

1508050058105  W/System.err(27517): 	at com.github.ayltai.newspaper.app.screen.DetailsPresenter$$Lambda$11.accept(Unknown Source)

1508050058105  W/System.err(27517): 	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)

1508050058106  W/System.err(27517): 	... 15 more


```

**Instabug Log:**
```

```

**User Steps:**
```
1508050016078 com.github.ayltai.newspaper.app.MainActivity was created.

1508050016649 com.github.ayltai.newspaper.app.MainActivity was started.

1508050016655 com.github.ayltai.newspaper.app.MainActivity was resumed.

1508050053034 In activity com.github.ayltai.newspaper.app.MainActivity: View of type android.view.View received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this issue because it is not valid for release build
