### ISSUE TITLE
io.reactivex.c.f: java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#110]
**Exception:** 	 io.reactivex.c.f: java.net.SocketTimeoutException: connect timed out
	at io.reactivex.i.a.a(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.single.c$a.a(SingleCreate.java:82)
	at com.github.ayltai.newspaper.b.bc.a(RssClient.java:53)
	at com.github.ayltai.newspaper.b.bh.a(Unknown Source)
	at io.reactivex.internal.d.u.onError(LambdaObserver.java:77)
	at io.reactivex.internal.d.a.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.i.k.a(HalfSerializer.java:133)
	at io.reactivex.internal.operators.observable.cm$a.a(ObservableRetryWhen.java:132)
	at io.reactivex.internal.operators.observable.cm$a$a.onError(ObservableRetryWhen.java:172)
	at io.reactivex.internal.operators.observable.ar$b.d(ObservableFlatMap.java:495)
	at io.reactivex.internal.operators.observable.ar$b.b(ObservableFlatMap.java:331)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ar$a.onError(ObservableFlatMap.java:571)
	at io.reactivex.internal.a.d.a(EmptyDisposable.java:63)
	at io.reactivex.internal.operators.observable.ap.subscribeActual(ObservableError.java:37)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ec$a.e(ObservableZip.java:205)
	at io.reactivex.internal.operators.observable.ec$b.a(ObservableZip.java:276)
	at io.reactivex.l.a$a.a(PublishSubject.java:264)
	at io.reactivex.l.a.a(PublishSubject.java:183)
	at io.reactivex.l.b.a(SerializedSubject.java:104)
	at io.reactivex.internal.operators.observable.cm$a.onError(ObservableRetryWhen.java:106)
	at io.reactivex.internal.operators.observable.dc$a.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.bv$a.a(ObservableObserveOn.java:276)
	at io.reactivex.internal.operators.observable.bv$a.b(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.bv$a.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:586)
	at okhttp3.internal.f.a.a(AndroidPlatform.java:69)
	at okhttp3.internal.a.c.a(RealConnection.java:238)
	at okhttp3.internal.a.c.a(RealConnection.java:158)
	at okhttp3.internal.a.g.a(StreamAllocation.java:256)
	at okhttp3.internal.a.g.a(StreamAllocation.java:134)
	at okhttp3.internal.a.g.a(StreamAllocation.java:113)
	at okhttp3.internal.a.a.a(ConnectInterceptor.java:42)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.a.a(CacheInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.y.i(RealCall.java:200)
	at okhttp3.y.b(RealCall.java:77)
	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	... 7 more

Caused by: 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:586)
	at okhttp3.internal.f.a.a(AndroidPlatform.java:69)
	at okhttp3.internal.a.c.a(RealConnection.java:238)
	at okhttp3.internal.a.c.a(RealConnection.java:158)
	at okhttp3.internal.a.g.a(StreamAllocation.java:256)
	at okhttp3.internal.a.g.a(StreamAllocation.java:134)
	at okhttp3.internal.a.g.a(StreamAllocation.java:113)
	at okhttp3.internal.a.a.a(ConnectInterceptor.java:42)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.a.a(CacheInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.y.i(RealCall.java:200)
	at okhttp3.y.b(RealCall.java:77)
	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 4

**URL:** 	 https://insta.co/crashes/9AhHizPx

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-08 12:16:04 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 1943.0/3533.0 MB

**Storage:** 	 12.626/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 

**Battery:** 	 34, Unplugged

**App Version:** 	 3.1.540-8a48291 (19)

**Duration:** 	 11

**User Data:** 	 

**Console Log:**
```
at okhttp3.internal.f.a.a(AndroidPlatform.java:69)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.c.a(RealConnection.java:238)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.c.a(RealConnection.java:158)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.g.a(StreamAllocation.java:256)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.g.a(StreamAllocation.java:134)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.g.a(StreamAllocation.java:113)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.a.a.a(ConnectInterceptor.java:42)

1507464964219  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.cache.a.a(CacheInterceptor.java:93)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:125)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)

1507464964220  W/System.err( 9084): 	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)

1507464964220  W/System.err( 9084): 	at okhttp3.y.i(RealCall.java:200)

1507464964220  W/System.err( 9084): 	at okhttp3.y.b(RealCall.java:77)

1507464964220  W/System.err( 9084): 	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)

1507464964220  W/System.err( 9084): 	at d.i.a(OkHttpCall.java:180)

1507464964220  W/System.err( 9084): 	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)

1507464964220  W/System.err( 9084): 	at io.reactivex.y.subscribe(Observable.java:10910)

1507464964220  W/System.err( 9084): 	at d.a.a.a.subscribeActual(BodyObservable.java:34)

1507464964220  W/System.err( 9084): 	at io.reactivex.y.subscribe(Observable.java:10910)

1507464964220  W/System.err( 9084): 	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)

1507464964220  W/System.err( 9084): 	at io.reactivex.y.subscribe(Observable.java:10910)

1507464964220  W/System.err( 9084): 	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)

1507464964220  W/System.err( 9084): 	at io.reactivex.y.subscribe(Observable.java:10910)

1507464964220  W/System.err( 9084): 	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)

1507464964220  W/System.err( 9084): 	at io.reactivex.af$a.run(Scheduler.java:452)

1507464964220  W/System.err( 9084): 	... 7 more

1507464964336  I/FirebaseCrash( 9084): Sending crashes


```

**Instabug Log:**
```

```

**User Steps:**
```
1507464952998 com.github.ayltai.newspaper.app.MainActivity was created.

1507464953205 com.github.ayltai.newspaper.app.MainActivity was started.

1507464953212 com.github.ayltai.newspaper.app.MainActivity was resumed.


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxxhdpi

**Comment by ayltai** [comment]
Merge this issue into https://github.com/ayltai/Newspaper/issues/111
