### ISSUE TITLE
io.reactivex.c.f: java.lang.RuntimeException: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#112]
**Exception:** 	 io.reactivex.c.f: java.lang.RuntimeException: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at io.reactivex.i.a.a(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.single.c$a.a(SingleCreate.java:82)
	at com.github.ayltai.newspaper.b.bc.a(RssClient.java:54)
	at com.github.ayltai.newspaper.b.bh.a(Unknown Source)
	at io.reactivex.internal.d.u.onError(LambdaObserver.java:77)
	at io.reactivex.internal.d.a.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.i.k.a(HalfSerializer.java:133)
	at io.reactivex.internal.operators.observable.cm$a.a(ObservableRetryWhen.java:132)
	at io.reactivex.internal.operators.observable.cm$a$a.onError(ObservableRetryWhen.java:172)
	at io.reactivex.internal.operators.observable.ar$b.d(ObservableFlatMap.java:495)
	at io.reactivex.internal.operators.observable.ar$b.b(ObservableFlatMap.java:331)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ar$a.onError(ObservableFlatMap.java:571)
	at io.reactivex.internal.a.d.a(EmptyDisposable.java:63)
	at io.reactivex.internal.operators.observable.ap.subscribeActual(ObservableError.java:37)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ec$a.e(ObservableZip.java:205)
	at io.reactivex.internal.operators.observable.ec$b.a(ObservableZip.java:276)
	at io.reactivex.l.a$a.a(PublishSubject.java:264)
	at io.reactivex.l.a.a(PublishSubject.java:183)
	at io.reactivex.l.b.a(SerializedSubject.java:104)
	at io.reactivex.internal.operators.observable.cm$a.onError(ObservableRetryWhen.java:106)
	at io.reactivex.internal.operators.observable.dc$a.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.bv$a.a(ObservableObserveOn.java:276)
	at io.reactivex.internal.operators.observable.bv$a.b(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.bv$a.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:44)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	... 7 more
Caused by: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:426)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:415)
	at org.simpleframework.xml.a.ce.b(LabelExtractor.java:300)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:265)
	at org.simpleframework.xml.a.ce.d(LabelExtractor.java:190)
	at org.simpleframework.xml.a.ce.c(LabelExtractor.java:174)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:142)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:95)
	at org.simpleframework.xml.a.eo.a(Support.java:242)
	at org.simpleframework.xml.a.en.b(StructureBuilder.java:245)
	at org.simpleframework.xml.a.en.a(StructureBuilder.java:185)
	at org.simpleframework.xml.a.cz.e(ObjectScanner.java:438)
	at org.simpleframework.xml.a.cz.a(ObjectScanner.java:371)
	at org.simpleframework.xml.a.cz.init(ObjectScanner.java:82)
	at org.simpleframework.xml.a.eb.a(ScannerFactory.java:81)
	at org.simpleframework.xml.a.eo.c(Support.java:357)
	at org.simpleframework.xml.a.el.i(Source.java:271)
	at org.simpleframework.xml.a.el.g(Source.java:317)
	at org.simpleframework.xml.a.t.a(Composite.java:198)
	at org.simpleframework.xml.a.t.a(Composite.java:148)
	at org.simpleframework.xml.a.ex.a(Traverser.java:92)
	at org.simpleframework.xml.a.dk.a(Persister.java:625)
	at org.simpleframework.xml.a.dk.a(Persister.java:606)
	at org.simpleframework.xml.a.dk.a(Persister.java:584)
	at org.simpleframework.xml.a.dk.a(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	... 21 more

Caused by: 
java.lang.RuntimeException: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:44)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:426)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:415)
	at org.simpleframework.xml.a.ce.b(LabelExtractor.java:300)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:265)
	at org.simpleframework.xml.a.ce.d(LabelExtractor.java:190)
	at org.simpleframework.xml.a.ce.c(LabelExtractor.java:174)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:142)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:95)
	at org.simpleframework.xml.a.eo.a(Support.java:242)
	at org.simpleframework.xml.a.en.b(StructureBuilder.java:245)
	at org.simpleframework.xml.a.en.a(StructureBuilder.java:185)
	at org.simpleframework.xml.a.cz.e(ObjectScanner.java:438)
	at org.simpleframework.xml.a.cz.a(ObjectScanner.java:371)
	at org.simpleframework.xml.a.cz.init(ObjectScanner.java:82)
	at org.simpleframework.xml.a.eb.a(ScannerFactory.java:81)
	at org.simpleframework.xml.a.eo.c(Support.java:357)
	at org.simpleframework.xml.a.el.i(Source.java:271)
	at org.simpleframework.xml.a.el.g(Source.java:317)
	at org.simpleframework.xml.a.t.a(Composite.java:198)
	at org.simpleframework.xml.a.t.a(Composite.java:148)
	at org.simpleframework.xml.a.ex.a(Traverser.java:92)
	at org.simpleframework.xml.a.dk.a(Persister.java:625)
	at org.simpleframework.xml.a.dk.a(Persister.java:606)
	at org.simpleframework.xml.a.dk.a(Persister.java:584)
	at org.simpleframework.xml.a.dk.a(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	... 21 more

Caused by: 
java.lang.NoSuchMethodException: init [interface org.simpleframework.xml.a.ag, interface org.simpleframework.xml.f, class org.simpleframework.xml.d.i]
	at java.lang.Class.getConstructor0(Class.java:2204)
	at java.lang.Class.getConstructor(Class.java:1683)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:426)
	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:415)
	at org.simpleframework.xml.a.ce.b(LabelExtractor.java:300)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:265)
	at org.simpleframework.xml.a.ce.d(LabelExtractor.java:190)
	at org.simpleframework.xml.a.ce.c(LabelExtractor.java:174)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:142)
	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:95)
	at org.simpleframework.xml.a.eo.a(Support.java:242)
	at org.simpleframework.xml.a.en.b(StructureBuilder.java:245)
	at org.simpleframework.xml.a.en.a(StructureBuilder.java:185)
	at org.simpleframework.xml.a.cz.e(ObjectScanner.java:438)
	at org.simpleframework.xml.a.cz.a(ObjectScanner.java:371)
	at org.simpleframework.xml.a.cz.init(ObjectScanner.java:82)
	at org.simpleframework.xml.a.eb.a(ScannerFactory.java:81)
	at org.simpleframework.xml.a.eo.c(Support.java:357)
	at org.simpleframework.xml.a.el.i(Source.java:271)
	at org.simpleframework.xml.a.el.g(Source.java:317)
	at org.simpleframework.xml.a.t.a(Composite.java:198)
	at org.simpleframework.xml.a.t.a(Composite.java:148)
	at org.simpleframework.xml.a.ex.a(Traverser.java:92)
	at org.simpleframework.xml.a.dk.a(Persister.java:625)
	at org.simpleframework.xml.a.dk.a(Persister.java:606)
	at org.simpleframework.xml.a.dk.a(Persister.java:584)
	at org.simpleframework.xml.a.dk.a(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 1

**URL:** 	 https://insta.co/crashes/AY-Zc7Ba

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-06 09:11:24 UTC

**Location:** 	 Kowloon, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2279.0/3533.0 MB

**Storage:** 	 17.559/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 9GAG

**Battery:** 	 100, Charging through USB cable

**App Version:** 	 3.1.535-6d70bd7 (18)

**Duration:** 	 6

**User Data:** 	 

**Console Log:**
```
1084451  W/System.err( 3460): 	at java.lang.Class.getConstructor(Class.java:1683)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:426)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce$a.a(LabelExtractor.java:415)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.b(LabelExtractor.java:300)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:265)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.d(LabelExtractor.java:190)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.c(LabelExtractor.java:174)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:142)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ce.a(LabelExtractor.java:95)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.eo.a(Support.java:242)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.en.b(StructureBuilder.java:245)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.en.a(StructureBuilder.java:185)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.cz.e(ObjectScanner.java:438)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.cz.a(ObjectScanner.java:371)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.cz.init(ObjectScanner.java:82)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.eb.a(ScannerFactory.java:81)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.eo.c(Support.java:357)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.el.i(Source.java:271)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.el.g(Source.java:317)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.t.a(Composite.java:198)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.t.a(Composite.java:148)

1507281084451  W/System.err( 3460): 	at org.simpleframework.xml.a.ex.a(Traverser.java:92)

1507281084452  W/System.err( 3460): 	at org.simpleframework.xml.a.dk.a(Persister.java:625)

1507281084452  W/System.err( 3460): 	at org.simpleframework.xml.a.dk.a(Persister.java:606)

1507281084452  W/System.err( 3460): 	at org.simpleframework.xml.a.dk.a(Persister.java:584)

1507281084452  W/System.err( 3460): 	at org.simpleframework.xml.a.dk.a(Persister.java:562)

1507281084452  W/System.err( 3460): 	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)

1507281084452  W/System.err( 3460): 	... 21 more

1507281084536  D/BigImageView( 3460): onCacheMiss /data/user/0/com.github.ayltai.newspaper/cache/54e158e3-3d4f-404c-9489-b231165a70a7.tmp

1507281084537  D/BigImageView( 3460): onCacheMiss /data/user/0/com.github.ayltai.newspaper/cache/124bf3be-f84b-470c-a98b-129010e894e6.tmp

1507281084539  I/ExifInterface_JNI( 3460): Raw image not detected

1507281084543  I/ExifInterface_JNI( 3460): Raw image not detected


```

**Instabug Log:**
```

```

**User Steps:**
```
1507281078482 com.github.ayltai.newspaper.app.MainActivity was created.

1507281078818 com.github.ayltai.newspaper.app.MainActivity was started.

1507281078829 com.github.ayltai.newspaper.app.MainActivity was resumed.


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this issue because it is not valid for release build
