### ISSUE TITLE
io.reactivex.c.f: java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#113]
**Exception:** 	 io.reactivex.c.f: java.net.SocketException: Software caused connection abort
	at io.reactivex.i.a.a(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.single.c$a.a(SingleCreate.java:82)
	at com.github.ayltai.newspaper.b.a.a(AppleDailyClient.java:100)
	at com.github.ayltai.newspaper.b.j.a(Unknown Source)
	at io.reactivex.internal.d.u.onError(LambdaObserver.java:77)
	at io.reactivex.internal.i.k.a(HalfSerializer.java:133)
	at io.reactivex.internal.operators.observable.cm$a.a(ObservableRetryWhen.java:132)
	at io.reactivex.internal.operators.observable.cm$a$a.onError(ObservableRetryWhen.java:172)
	at io.reactivex.internal.operators.observable.ar$b.d(ObservableFlatMap.java:495)
	at io.reactivex.internal.operators.observable.ar$b.b(ObservableFlatMap.java:331)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ar$a.onError(ObservableFlatMap.java:571)
	at io.reactivex.internal.a.d.a(EmptyDisposable.java:63)
	at io.reactivex.internal.operators.observable.ap.subscribeActual(ObservableError.java:37)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ec$a.e(ObservableZip.java:205)
	at io.reactivex.internal.operators.observable.ec$b.a(ObservableZip.java:276)
	at io.reactivex.l.a$a.a(PublishSubject.java:264)
	at io.reactivex.l.a.a(PublishSubject.java:183)
	at io.reactivex.l.b.a(SerializedSubject.java:104)
	at io.reactivex.internal.operators.observable.cm$a.onError(ObservableRetryWhen.java:106)
	at io.reactivex.internal.operators.observable.dc$a.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.bv$a.a(ObservableObserveOn.java:276)
	at io.reactivex.internal.operators.observable.bv$a.b(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.bv$a.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:151)
	at java.net.SocketInputStream.read(SocketInputStream.java:120)
	at c.l$2.a(Okio.java:139)
	at c.a$2.a(AsyncTimeout.java:237)
	at c.n.a(RealBufferedSource.java:345)
	at c.n.c(RealBufferedSource.java:217)
	at c.n.r(RealBufferedSource.java:211)
	at okhttp3.internal.c.a.a(Http1Codec.java:187)
	at okhttp3.internal.b.b.a(CallServerInterceptor.java:88)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.a.a.a(ConnectInterceptor.java:45)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.a.a(CacheInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.y.i(RealCall.java:200)
	at okhttp3.y.b(RealCall.java:77)
	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	... 7 more

Caused by: 
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:151)
	at java.net.SocketInputStream.read(SocketInputStream.java:120)
	at c.l$2.a(Okio.java:139)
	at c.a$2.a(AsyncTimeout.java:237)
	at c.n.a(RealBufferedSource.java:345)
	at c.n.c(RealBufferedSource.java:217)
	at c.n.r(RealBufferedSource.java:211)
	at okhttp3.internal.c.a.a(Http1Codec.java:187)
	at okhttp3.internal.b.b.a(CallServerInterceptor.java:88)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.a.a.a(ConnectInterceptor.java:45)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.a.a(CacheInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.internal.b.a.a(BridgeInterceptor.java:93)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.j.a(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.b.g.a(RealInterceptorChain.java:121)
	at okhttp3.y.i(RealCall.java:200)
	at okhttp3.y.b(RealCall.java:77)
	at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 5

**URL:** 	 https://insta.co/crashes/DyKGGo5v

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-12 01:56:59 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2654.0/3533.0 MB

**Storage:** 	 13.548/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 

**Battery:** 	 96, Unplugged

**App Version:** 	 3.1.540-8a48291 (19)

**Duration:** 	 17

**User Data:** 	 

**Console Log:**
```
Adapter.call(Executors.java:428)

1507773417915  E/Beta    (14101): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

1507773417915  E/Beta    (14101): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)

1507773417915  E/Beta    (14101): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

1507773417915  E/Beta    (14101): 	at java.lang.Thread.run(Thread.java:762)

1507773417915  E/Beta    (14101): Caused by: java.net.ConnectException: Network is unreachable

1507773417915  E/Beta    (14101): 	at java.net.PlainSocketImpl.socketConnect(Native Method)

1507773417915  E/Beta    (14101): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)

1507773417915  E/Beta    (14101): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)

1507773417915  E/Beta    (14101): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)

1507773417915  E/Beta    (14101): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)

1507773417915  E/Beta    (14101): 	at java.net.Socket.connect(Socket.java:586)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.Connection.connectSocket(Connection.java:1432)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.Connection.connect(Connection.java:1390)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1667)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:567)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)

1507773417915  E/Beta    (14101): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)

1507773417915  E/Beta    (14101): 	at com.google.firebase.perf.network.e.h(Unknown Source)

1507773417915  E/Beta    (14101): 	at com.google.firebase.perf.network.d.getResponseCode(Unknown Source)

1507773417915  E/Beta    (14101): 	at io.fabric.sdk.android.services.network.HttpRequest.code(HttpRequest.java:1353)

1507773417915  E/Beta    (14101): 	... 16 more


```

**Instabug Log:**
```

```

**User Steps:**
```
1507773400573 com.github.ayltai.newspaper.app.MainActivity was created.

1507773400779 com.github.ayltai.newspaper.app.MainActivity was started.

1507773400781 com.github.ayltai.newspaper.app.MainActivity was resumed.

1507773415546 com.github.ayltai.newspaper.app.MainActivity was paused.

1507773416185 com.github.ayltai.newspaper.app.MainActivity was stopped.


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxxhdpi

**Comment by ayltai** [comment]
Merge this issue into https://github.com/ayltai/Newspaper/issues/111
