### ISSUE TITLE
io.reactivex.c.f: java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#114]
**Exception:** 	 io.reactivex.c.f: java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at io.reactivex.i.a.a(RxJavaPlugins.java:349)
	at io.reactivex.internal.operators.single.c$a.a(SingleCreate.java:82)
	at com.github.ayltai.newspaper.b.bc.a(RssClient.java:54)
	at com.github.ayltai.newspaper.b.bh.a(Unknown Source)
	at io.reactivex.internal.d.u.onError(LambdaObserver.java:77)
	at io.reactivex.internal.d.a.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.i.k.a(HalfSerializer.java:133)
	at io.reactivex.internal.operators.observable.cm$a.a(ObservableRetryWhen.java:132)
	at io.reactivex.internal.operators.observable.cm$a$a.onError(ObservableRetryWhen.java:172)
	at io.reactivex.internal.operators.observable.ar$b.d(ObservableFlatMap.java:495)
	at io.reactivex.internal.operators.observable.ar$b.b(ObservableFlatMap.java:331)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:323)
	at io.reactivex.internal.operators.observable.ar$a.onError(ObservableFlatMap.java:571)
	at io.reactivex.internal.a.d.a(EmptyDisposable.java:63)
	at io.reactivex.internal.operators.observable.ap.subscribeActual(ObservableError.java:37)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:162)
	at io.reactivex.internal.operators.observable.ar$b.a(ObservableFlatMap.java:139)
	at io.reactivex.internal.operators.observable.ec$a.e(ObservableZip.java:205)
	at io.reactivex.internal.operators.observable.ec$b.a(ObservableZip.java:276)
	at io.reactivex.l.a$a.a(PublishSubject.java:264)
	at io.reactivex.l.a.a(PublishSubject.java:183)
	at io.reactivex.l.b.a(SerializedSubject.java:104)
	at io.reactivex.internal.operators.observable.cm$a.onError(ObservableRetryWhen.java:106)
	at io.reactivex.internal.operators.observable.dc$a.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.bv$a.a(ObservableObserveOn.java:276)
	at io.reactivex.internal.operators.observable.bv$a.b(ObservableObserveOn.java:172)
	at io.reactivex.internal.operators.observable.bv$a.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:44)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	... 7 more
Caused by: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at org.simpleframework.xml.core.ClassInstantiator.getInstance(ClassInstantiator.java:112)
	at org.simpleframework.xml.core.Composite$Injector.readInject(Composite.java:1458)
	at org.simpleframework.xml.core.Composite$Injector.read(Composite.java:1435)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.readSection(Composite.java:327)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:443)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	... 21 more

Caused by: 
java.lang.RuntimeException: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:44)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at org.simpleframework.xml.core.ClassInstantiator.getInstance(ClassInstantiator.java:112)
	at org.simpleframework.xml.core.Composite$Injector.readInject(Composite.java:1458)
	at org.simpleframework.xml.core.Composite$Injector.read(Composite.java:1435)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.readSection(Composite.java:327)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:443)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	... 21 more

Caused by: 
org.simpleframework.xml.core.PersistenceException: Constructor not matched for class com.github.ayltai.newspaper.f.a
	at org.simpleframework.xml.core.ClassInstantiator.getInstance(ClassInstantiator.java:112)
	at org.simpleframework.xml.core.Composite$Injector.readInject(Composite.java:1458)
	at org.simpleframework.xml.core.Composite$Injector.read(Composite.java:1435)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.readSection(Composite.java:327)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:443)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)
	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:23)
	at d.o.a(ServiceMethod.java:119)
	at d.i.a(OkHttpCall.java:218)
	at d.i.a(OkHttpCall.java:180)
	at d.a.a.c.subscribeActual(CallExecuteObservable.java:41)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at d.a.a.a.subscribeActual(BodyObservable.java:34)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bw.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.bv.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.y.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.dc$b.run(ObservableSubscribeOn.java:96)
	at io.reactivex.af$a.run(Scheduler.java:452)
	at io.reactivex.internal.f.n.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.f.n.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 2

**URL:** 	 https://insta.co/crashes/DUbNVd2X

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-06 12:13:35 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2511.0/3533.0 MB

**Storage:** 	 17.564/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: Radiohead

**Battery:** 	 96, Unplugged

**App Version:** 	 3.1.533-9659077 (18)

**Duration:** 	 11

**User Data:** 	 

**Console Log:**
```


1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.read(Composite.java:201)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.read(Composite.java:148)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readSection(Composite.java:327)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.readElements(Composite.java:443)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.read(Composite.java:201)

1507292014987  W/System.err(20755): 	at org.simpleframework.xml.core.Composite.read(Composite.java:148)

1507292014988  W/System.err(20755): 	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)

1507292014988  W/System.err(20755): 	at org.simpleframework.xml.core.Persister.read(Persister.java:625)

1507292014988  W/System.err(20755): 	at org.simpleframework.xml.core.Persister.read(Persister.java:606)

1507292014988  W/System.err(20755): 	at org.simpleframework.xml.core.Persister.read(Persister.java:584)

1507292014988  W/System.err(20755): 	at org.simpleframework.xml.core.Persister.read(Persister.java:562)

1507292014988  W/System.err(20755): 	at d.b.b.c.a(SimpleXmlResponseBodyConverter.java:36)

1507292014988  W/System.err(20755): 	... 21 more

1507292015131  D/ViewRootImpl@6a7df40[MainActivity](20755): ViewPostImeInputStage processPointer 0

1507292015180  D/ViewRootImpl@6a7df40[MainActivity](20755): ViewPostImeInputStage processPointer 1


```

**Instabug Log:**
```

```

**User Steps:**
```
1507292002497 com.github.ayltai.newspaper.app.MainActivity was created.

1507292003038 com.github.ayltai.newspaper.app.MainActivity was started.

1507292003047 com.github.ayltai.newspaper.app.MainActivity was resumed.

1507292006939 In activity com.github.ayltai.newspaper.app.MainActivity: View(image) of type com.davemorrissey.labs.subscaleview.b received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this issue because it is not valid for release build
