### ISSUE TITLE
io.reactivex.c.d: Illegal Argument: Provided schema version 1 is less than last set version 17.

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#115]
**Exception:** 	 io.reactivex.c.d: Illegal Argument: Provided schema version 1 is less than last set version 17.
	at io.reactivex.internal.b.a$ag.a(Functions.java:704)
	at io.reactivex.internal.b.a$ag.a(Functions.java:701)
	at io.reactivex.internal.d.k.onError(ConsumerSingleObserver.java:47)
	at io.reactivex.internal.operators.single.al$a.onError(SingleSubscribeOn.java:73)
	at io.reactivex.internal.operators.single.ai$a.run(SingleObserveOn.java:79)
	at io.reactivex.internal.f.m.a(ScheduledDirectTask.java:38)
	at io.reactivex.internal.f.m.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Provided schema version 1 is less than last set version 17.
	at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.SharedRealm.init(SharedRealm.java:180)
	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
	at io.realm.a.init(BaseRealm.java:124)
	at io.realm.a.init(BaseRealm.java:93)
	at io.realm.o.init(Realm.java:150)
	at io.realm.o.a(Realm.java:417)
	at io.realm.p.b(RealmCache.java:348)
	at io.realm.p.a(RealmCache.java:281)
	at io.realm.o.k(Realm.java:325)
	at com.github.ayltai.newspaper.c.d.a(DataModule.java:39)
	at com.github.ayltai.newspaper.c.e.a(DataModule_ProvideRealmFactory.java:23)
	at com.github.ayltai.newspaper.c.e.b(DataModule_ProvideRealmFactory.java:8)
	at com.github.ayltai.newspaper.c.a.b(DaggerDataComponent.java:32)
	at com.github.ayltai.newspaper.app.MainActivity.b(MainActivity.java:81)
	at com.github.ayltai.newspaper.app.h.a(Unknown Source)
	at io.reactivex.internal.operators.single.c.subscribeActual(SingleCreate.java:39)
	at io.reactivex.ag.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.ai.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.ag.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.al$a.run(SingleSubscribeOn.java:89)
	... 6 more

Caused by: 
java.lang.IllegalArgumentException: Illegal Argument: Provided schema version 1 is less than last set version 17.
	at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.SharedRealm.init(SharedRealm.java:180)
	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)
	at io.realm.a.init(BaseRealm.java:124)
	at io.realm.a.init(BaseRealm.java:93)
	at io.realm.o.init(Realm.java:150)
	at io.realm.o.a(Realm.java:417)
	at io.realm.p.b(RealmCache.java:348)
	at io.realm.p.a(RealmCache.java:281)
	at io.realm.o.k(Realm.java:325)
	at com.github.ayltai.newspaper.c.d.a(DataModule.java:39)
	at com.github.ayltai.newspaper.c.e.a(DataModule_ProvideRealmFactory.java:23)
	at com.github.ayltai.newspaper.c.e.b(DataModule_ProvideRealmFactory.java:8)
	at com.github.ayltai.newspaper.c.a.b(DaggerDataComponent.java:32)
	at com.github.ayltai.newspaper.app.MainActivity.b(MainActivity.java:81)
	at com.github.ayltai.newspaper.app.h.a(Unknown Source)
	at io.reactivex.internal.operators.single.c.subscribeActual(SingleCreate.java:39)
	at io.reactivex.ag.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.ai.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.ag.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.al$a.run(SingleSubscribeOn.java:89)
	at io.reactivex.internal.f.m.a(ScheduledDirectTask.java:38)
	at io.reactivex.internal.f.m.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 3

**URL:** 	 https://insta.co/crashes/dUy9hy1x

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-06 16:34:36 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2604.0/3533.0 MB

**Storage:** 	 12.972/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: Radiohead

**Battery:** 	 100, Unplugged

**App Version:** 	 3.1.538-eb171a0 (19)

**Duration:** 	 0

**User Data:** 	 

**Console Log:**
```
realm.internal.SharedRealm.init(SharedRealm.java:180)

1507307676373  W/System.err(16331): 	at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:227)

1507307676373  W/System.err(16331): 	at io.realm.a.init(BaseRealm.java:124)

1507307676373  W/System.err(16331): 	at io.realm.a.init(BaseRealm.java:93)

1507307676373  W/System.err(16331): 	at io.realm.o.init(Realm.java:150)

1507307676373  W/System.err(16331): 	at io.realm.o.a(Realm.java:417)

1507307676373  W/System.err(16331): 	at io.realm.p.b(RealmCache.java:348)

1507307676373  W/System.err(16331): 	at io.realm.p.a(RealmCache.java:281)

1507307676373  W/System.err(16331): 	at io.realm.o.k(Realm.java:325)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.c.d.a(DataModule.java:39)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.c.e.a(DataModule_ProvideRealmFactory.java:23)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.c.e.b(DataModule_ProvideRealmFactory.java:8)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.c.a.b(DaggerDataComponent.java:32)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.app.MainActivity.b(MainActivity.java:81)

1507307676373  W/System.err(16331): 	at com.github.ayltai.newspaper.app.h.a(Unknown Source)

1507307676373  W/System.err(16331): 	at io.reactivex.internal.operators.single.c.subscribeActual(SingleCreate.java:39)

1507307676373  W/System.err(16331): 	at io.reactivex.ag.subscribe(Single.java:2779)

1507307676373  W/System.err(16331): 	at io.reactivex.internal.operators.single.ai.subscribeActual(SingleObserveOn.java:35)

1507307676373  W/System.err(16331): 	at io.reactivex.ag.subscribe(Single.java:2779)

1507307676373  W/System.err(16331): 	at io.reactivex.internal.operators.single.al$a.run(SingleSubscribeOn.java:89)

1507307676373  W/System.err(16331): 	... 6 more

1507307676382  I/pittpatt(16331): wrapper.cc:442] JNI_OnLoad successful

1507307676382  I/Vision  (16331): libmobile_vision_face.so library load status: true

1507307676399  E/FA      (16331): Name must consist of letters, digits or _ (underscores). Type, name: event, App Open

1507307676401  I/FA      (16331): Tag Manager is not found and thus will not be used

1507307676432  I/AppCompatViewInflater(16331): app:theme is now deprecated. Please move to using android:theme instead.

1507307676515  D/TextView(16331): setTypeface with style : 0

1507307676515  D/TextView(16331): setTypeface with style : 0

1507307676520  D/TextView(16331): setTypeface with style : 0

1507307676538  D/TextView(16331): setTypeface with style : 0

1507307676541  D/TextView(16331): setTypeface with style : 0

1507307676543  D/TextView(16331): setTypeface with style : 0

1507307676546  D/TextView(16331): setTypeface with style : 0

1507307676569  D/TextView(16331): setTypeface with style : 0

1507307676572  D/TextView(16331): setTypeface with style : 0

1507307676574  D/TextView(16331): setTypeface with style : 0


```

**Instabug Log:**
```

```

**User Steps:**
```
1507307676220 com.github.ayltai.newspaper.app.MainActivity was created.

1507307676614 com.github.ayltai.newspaper.app.MainActivity was started.


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxxhdpi

**Comment by ayltai** [comment]
Close this issue because it is not valid for release build
