### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method void com.github.ayltai.newspaper.speech.SimpleTextToSpeech.shutdown() on a null object reference

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#117]
**Exception:** 	 java.lang.NullPointerException: Attempt to invoke virtual method void com.github.ayltai.newspaper.speech.SimpleTextToSpeech.shutdown() on a null object reference
	at com.github.ayltai.newspaper.app.screen.DetailsScreen.lambda$textToSpeech$3(DetailsScreen.java:346)
	at com.github.ayltai.newspaper.app.screen.DetailsScreen$$Lambda$4.accept(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Number:** 	 9

**URL:** 	 https://insta.co/crashes/wJaKD2bZ

**Status:** 	 Closed

**Email:** 	 

**Reported At:** 	 2017-10-15 07:58:30 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 Genymotion Google Pixel - 7.1.0 - API 25 - 1080x1920

**Memory:** 	 378.0/1497.0 MB

**Storage:** 	 0.118/12.756 GB

**Connectivity:** 	 Carrier: Android, WiFi: WiredSSID

**Battery:** 	 100, Unplugged

**App Version:** 	 3.2.629-df3e632 (20)

**Duration:** 	 225

**User Data:** 	 

**Console Log:**
```
220): Content-Length: 231252

1508054307950  D/OkHttp  ( 2220): Connection: keep-alive

1508054307950  D/OkHttp  ( 2220): ETag: 59e31329-38754

1508054307950  D/OkHttp  ( 2220): X-Content-Type-Options: nosniff

1508054307950  D/OkHttp  ( 2220): X-XSS-Protection: 1; mode=block

1508054307950  D/OkHttp  ( 2220): Vary: Accept, Accept-Encoding

1508054307950  D/OkHttp  ( 2220): Expires: Sun, 15 Oct 2017 08:03:27 GMT

1508054307950  D/OkHttp  ( 2220): Cache-Control: max-age=300

1508054307950  D/OkHttp  ( 2220): Accept-Ranges: bytes

1508054307950  D/OkHttp  ( 2220): -- END HTTP

1508054307952  W/GooglePlayServicesUtil( 2220): Google Play Store is missing.

1508054308002  D/BigImageView( 2220): onCacheMiss /data/user/0/com.github.ayltai.newspaper/cache/9a7afd8d-c367-466e-a0a4-c5c4ec7ff592.tmp

1508054308003  I/ExifInterface_JNI( 2220): Raw image not detected

1508054308017  W/unknown:CloseableReference( 2220): Finalized without closing: 6af2e7 935fe94 (type = NativePooledByteBuffer)

1508054308017  W/unknown:CloseableReference( 2220): Finalized without closing: a06ad3d 7ce8932 (type = CloseableStaticBitmap)

1508054308025  I/ExifInterface_JNI( 2220): Raw image not detected

1508054310838  W/AutoValue_SimpleTextToSpeech( 2220): TTS initialization error -1

1508054310853  W/System.err( 2220): java.lang.NullPointerException: Attempt to invoke virtual method void com.github.ayltai.newspaper.speech.SimpleTextToSpeech.shutdown() on a null object reference

1508054310853  W/System.err( 2220): 	at com.github.ayltai.newspaper.app.screen.DetailsScreen.lambda$textToSpeech$3(DetailsScreen.java:346)

1508054310853  W/System.err( 2220): 	at com.github.ayltai.newspaper.app.screen.DetailsScreen$$Lambda$4.accept(Unknown Source)

1508054310853  W/System.err( 2220): 	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)

1508054310853  W/System.err( 2220): 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)

1508054310853  W/System.err( 2220): 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)

1508054310853  W/System.err( 2220): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)

1508054310853  W/System.err( 2220): 	at android.os.Handler.handleCallback(Handler.java:751)

1508054310853  W/System.err( 2220): 	at android.os.Handler.dispatchMessage(Handler.java:95)

1508054310853  W/System.err( 2220): 	at android.os.Looper.loop(Looper.java:154)

1508054310853  W/System.err( 2220): 	at android.app.ActivityThread.main(ActivityThread.java:6119)

1508054310853  W/System.err( 2220): 	at java.lang.reflect.Method.invoke(Native Method)

1508054310853  W/System.err( 2220): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)

1508054310853  W/System.err( 2220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


```

**Instabug Log:**
```

```

**User Steps:**
```
1508054085460 com.github.ayltai.newspaper.app.MainActivity was created.

1508054085537 com.github.ayltai.newspaper.app.MainActivity was started.

1508054085586 com.github.ayltai.newspaper.app.MainActivity was resumed.

1508054307823 In activity com.github.ayltai.newspaper.app.MainActivity: View(title) of type android.support.v7.widget.AppCompatTextView received a click event

1508054310823 In activity com.github.ayltai.newspaper.app.MainActivity: View(action_text_to_speech) of type android.support.v7.widget.AppCompatImageView received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1080x1920

**Density:** 	 xhdpi

**Comment by ayltai** [comment]
Close this issue because it is not valid for release build
