### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#119]
**Exception:** 	 io.reactivex.exceptions.OnErrorNotImplementedException: Jetty ALPN/NPN has not been properly configured.
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
	at com.github.ayltai.newspaper.app.widget.ItemView.lambda$onAttachedToWindow$0(ItemView.java:140)
	at com.github.ayltai.newspaper.app.widget.ItemView$$Lambda$1.accept(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
	at android.view.View.performClick(View.java:6213)
	at android.view.View$PerformClick.run(View.java:23645)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.init(NettyChannelBuilder.java:525)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.init(NettyChannelBuilder.java:518)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.init(NettyChannelBuilder.java:457)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:326)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:315)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:131)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
	at com.google.api.gax.grpc.GrpcTransportProvider.getTransport(GrpcTransportProvider.java:98)
	at com.google.api.gax.grpc.GrpcTransportProvider.getTransport(GrpcTransportProvider.java:59)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:97)
	at com.google.cloud.language.v1beta2.stub.GrpcLanguageServiceStub.create(GrpcLanguageServiceStub.java:122)
	at com.google.cloud.language.v1beta2.LanguageServiceSettings.createStub(LanguageServiceSettings.java:135)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.init(LanguageServiceClient.java:136)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.create(LanguageServiceClient.java:118)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.create(LanguageServiceClient.java:109)
	at com.github.ayltai.newspaper.language.LanguageModule.provideLanguageServiceClient(LanguageModule.java:24)
	at com.github.ayltai.newspaper.language.LanguageModule_ProvideLanguageServiceClientFactory.get(LanguageModule_ProvideLanguageServiceClientFactory.java:20)
	at com.github.ayltai.newspaper.language.LanguageModule_ProvideLanguageServiceClientFactory.get(LanguageModule_ProvideLanguageServiceClientFactory.java:8)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.github.ayltai.newspaper.language.DaggerLanguageComponent.languageServiceClient(DaggerLanguageComponent.java:36)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.analyzeEntities(DetailsPresenter.java:192)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.bindModel(DetailsPresenter.java:61)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.bindModel(DetailsPresenter.java:40)
	at com.github.ayltai.newspaper.app.FlowController.lambda$attachNewBase$0(FlowController.java:101)
	at com.github.ayltai.newspaper.app.FlowController$$Lambda$1.changeKey(Unknown Source)
	at flow.KeyDispatcher.changeKey(KeyDispatcher.java:97)
	at flow.KeyDispatcher.dispatch(KeyDispatcher.java:91)
	at flow.Flow$PendingTraversal.dispatch(Flow.java:422)
	at flow.Flow$4.doExecute(Flow.java:270)
	at flow.Flow$PendingTraversal.execute(Flow.java:430)
	at flow.Flow.move(Flow.java:317)
	at flow.Flow.set(Flow.java:235)
	at com.github.ayltai.newspaper.app.view.ItemPresenter.onClick(ItemPresenter.java:128)
	at com.github.ayltai.newspaper.app.view.ItemPresenter.lambda$onViewAttached$0(ItemPresenter.java:214)
	at com.github.ayltai.newspaper.app.view.ItemPresenter$$Lambda$1.accept(Unknown Source)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 15 more

Caused by: 
java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.init(NettyChannelBuilder.java:525)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.init(NettyChannelBuilder.java:518)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.init(NettyChannelBuilder.java:457)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:326)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:315)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.createChannel(InstantiatingChannelProvider.java:131)
	at com.google.api.gax.grpc.InstantiatingChannelProvider.getChannel(InstantiatingChannelProvider.java:116)
	at com.google.api.gax.grpc.GrpcTransportProvider.getTransport(GrpcTransportProvider.java:98)
	at com.google.api.gax.grpc.GrpcTransportProvider.getTransport(GrpcTransportProvider.java:59)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:97)
	at com.google.cloud.language.v1beta2.stub.GrpcLanguageServiceStub.create(GrpcLanguageServiceStub.java:122)
	at com.google.cloud.language.v1beta2.LanguageServiceSettings.createStub(LanguageServiceSettings.java:135)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.init(LanguageServiceClient.java:136)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.create(LanguageServiceClient.java:118)
	at com.google.cloud.language.v1beta2.LanguageServiceClient.create(LanguageServiceClient.java:109)
	at com.github.ayltai.newspaper.language.LanguageModule.provideLanguageServiceClient(LanguageModule.java:24)
	at com.github.ayltai.newspaper.language.LanguageModule_ProvideLanguageServiceClientFactory.get(LanguageModule_ProvideLanguageServiceClientFactory.java:20)
	at com.github.ayltai.newspaper.language.LanguageModule_ProvideLanguageServiceClientFactory.get(LanguageModule_ProvideLanguageServiceClientFactory.java:8)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.github.ayltai.newspaper.language.DaggerLanguageComponent.languageServiceClient(DaggerLanguageComponent.java:36)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.analyzeEntities(DetailsPresenter.java:192)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.bindModel(DetailsPresenter.java:61)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.bindModel(DetailsPresenter.java:40)
	at com.github.ayltai.newspaper.app.FlowController.lambda$attachNewBase$0(FlowController.java:101)
	at com.github.ayltai.newspaper.app.FlowController$$Lambda$1.changeKey(Unknown Source)
	at flow.KeyDispatcher.changeKey(KeyDispatcher.java:97)
	at flow.KeyDispatcher.dispatch(KeyDispatcher.java:91)
	at flow.Flow$PendingTraversal.dispatch(Flow.java:422)
	at flow.Flow$4.doExecute(Flow.java:270)
	at flow.Flow$PendingTraversal.execute(Flow.java:430)
	at flow.Flow.move(Flow.java:317)
	at flow.Flow.set(Flow.java:235)
	at com.github.ayltai.newspaper.app.view.ItemPresenter.onClick(ItemPresenter.java:128)
	at com.github.ayltai.newspaper.app.view.ItemPresenter.lambda$onViewAttached$0(ItemPresenter.java:214)
	at com.github.ayltai.newspaper.app.view.ItemPresenter$$Lambda$1.accept(Unknown Source)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.processors.PublishProcessor$PublishSubscription.onNext(PublishProcessor.java:315)
	at io.reactivex.processors.PublishProcessor.onNext(PublishProcessor.java:197)
	at com.github.ayltai.newspaper.app.widget.ItemView.lambda$onAttachedToWindow$0(ItemView.java:140)
	at com.github.ayltai.newspaper.app.widget.ItemView$$Lambda$1.accept(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
	at android.view.View.performClick(View.java:6213)
	at android.view.View$PerformClick.run(View.java:23645)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Number:** 	 11

**URL:** 	 https://insta.co/crashes/McD7zy94

**Status:** 	 New

**Email:** 	 

**Reported At:** 	 2017-10-17 08:58:12 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2393.0/3533.0 MB

**Storage:** 	 18.963/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 9GAG

**Battery:** 	 100, Charging through USB cable

**App Version:** 	 3.2.- (20)

**Duration:** 	 46

**User Data:** 	 

**Console Log:**
```
resenter.bindModel(DetailsPresenter.java:61)

1508230692555  W/System.err(23463): 	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.bindModel(DetailsPresenter.java:40)

1508230692556  W/System.err(23463): 	at com.github.ayltai.newspaper.app.FlowController.lambda$attachNewBase$0(FlowController.java:101)

1508230692556  W/System.err(23463): 	at com.github.ayltai.newspaper.app.FlowController$$Lambda$1.changeKey(Unknown Source)

1508230692556  W/System.err(23463): 	at flow.KeyDispatcher.changeKey(KeyDispatcher.java:97)

1508230692556  W/System.err(23463): 	at flow.KeyDispatcher.dispatch(KeyDispatcher.java:91)

1508230692556  W/System.err(23463): 	at flow.Flow$PendingTraversal.dispatch(Flow.java:422)

1508230692556  W/System.err(23463): 	at flow.Flow$4.doExecute(Flow.java:270)

1508230692556  W/System.err(23463): 	at flow.Flow$PendingTraversal.execute(Flow.java:430)

1508230692556  W/System.err(23463): 	at flow.Flow.move(Flow.java:317)

1508230692556  W/System.err(23463): 	at flow.Flow.set(Flow.java:235)

1508230692556  W/System.err(23463): 	at com.github.ayltai.newspaper.app.view.ItemPresenter.onClick(ItemPresenter.java:128)

1508230692556  W/System.err(23463): 	at com.github.ayltai.newspaper.app.view.ItemPresenter.lambda$onViewAttached$0(ItemPresenter.java:214)

1508230692556  W/System.err(23463): 	at com.github.ayltai.newspaper.app.view.ItemPresenter$$Lambda$1.accept(Unknown Source)

1508230692556  W/System.err(23463): 	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)

1508230692556  W/System.err(23463): 	... 15 more

1508230692559  V/MixpanelAPI.PIdentity(23463): Loading Super Properties 

1508230692583  V/MixpanelAPI.Messages(23463): Queuing event for sending later (Thread 265076)

1508230692584  V/MixpanelAPI.Messages(23463):     event:$ae_crashed,properties:mp_lib:android,$lib_version:5.2.1,$os:Android,$os_version:7.0,$manufacturer:samsung,$brand:samsung,$model:SM-G930F,$google_play_services:available,$screen_dpi:560,$screen_height:2560,$screen_width:1440,$app_version:3.2.-,$app_version_string:3.2.-,$app_release:20,$app_build_number:20,$has_nfc:true,$has_telephone:true,$carrier:csl.,$wifi:true,$bluetooth_version:ble,token:23357b9291bde449aa7c64ef85bdff47,time:1508230692,distinct_id:4f898d53-5794-4f7e-be54-64940ffbf138,$ae_crashed_reason:io.reactivex.exceptions.OnErrorNotImplementedException: Jetty ALPN\/NPN has not been properly configured. (Thread 265076)

1508230692613  V/MixpanelAPI.Messages(23463): Flushing queue due to scheduled or forced flush (Thread 265076)

1508230692615  V/MixpanelAPI.Message(23463): ConnectivityManager says we are online

1508230692633  V/MixpanelAPI.Message(23463): Attempting request to https://api.mixpanel.com/track?ip=1

1508230692636  I/System.out(23463): (HTTPLog)-Static: isSBSettingEnabled false

1508230692636  I/System.out(23463): (HTTPLog)-Static: isSBSettingEnabled false


```

**Instabug Log:**
```

```

**User Steps:**
```
1508230645458 com.github.ayltai.newspaper.app.MainActivity was created.

1508230646045 com.github.ayltai.newspaper.app.MainActivity was started.

1508230646060 com.github.ayltai.newspaper.app.MainActivity was resumed.

1508230692171 In activity com.github.ayltai.newspaper.app.MainActivity: View of type android.view.View received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this because it is invalid for release build

**Comment by ayltai** [comment]
Close this because it is not valid for release build
