### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: Null accessToken

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#121]
**Exception:** 	 io.reactivex.exceptions.OnErrorNotImplementedException: Null accessToken
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Null accessToken
	at com.github.ayltai.newspaper.language.$AutoValue_AuthToken.init($AutoValue_AuthToken.java:21)
	at com.github.ayltai.newspaper.language.AutoValue_AuthToken.init(AutoValue_AuthToken.java:20)
	at com.github.ayltai.newspaper.language.AuthToken.load(AuthToken.java:69)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.lambda$analyzeEntities$12(DetailsPresenter.java:191)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter$$Lambda$13.call(Unknown Source)
	at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

Caused by: 
java.lang.NullPointerException: Null accessToken
	at com.github.ayltai.newspaper.language.$AutoValue_AuthToken.init($AutoValue_AuthToken.java:21)
	at com.github.ayltai.newspaper.language.AutoValue_AuthToken.init(AutoValue_AuthToken.java:20)
	at com.github.ayltai.newspaper.language.AuthToken.load(AuthToken.java:69)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter.lambda$analyzeEntities$12(DetailsPresenter.java:191)
	at com.github.ayltai.newspaper.app.screen.DetailsPresenter$$Lambda$13.call(Unknown Source)
	at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 12

**URL:** 	 https://insta.co/crashes/PzGeDUJH

**Status:** 	 New

**Email:** 	 

**Reported At:** 	 2017-10-19 09:28:34 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2517.0/3533.0 MB

**Storage:** 	 19.22/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 9GAG

**Battery:** 	 100, Charging through USB cable

**App Version:** 	 3.2.- (20)

**Duration:** 	 45

**User Data:** 	 

**Console Log:**
```
27084.jpeg (117ms)

1508405313832  D/OkHttp  (12475): Date: Thu, 19 Oct 2017 09:28:34 GMT

1508405313832  D/OkHttp  (12475): Content-Type: image/jpeg

1508405313832  D/OkHttp  (12475): Content-Length: 177644

1508405313832  D/OkHttp  (12475): Connection: keep-alive

1508405313832  D/OkHttp  (12475): ETag: 59e86ebc-2b5ec

1508405313832  D/OkHttp  (12475): X-Content-Type-Options: nosniff

1508405313832  D/OkHttp  (12475): X-XSS-Protection: 1; mode=block

1508405313832  D/OkHttp  (12475): Vary: Accept, Accept-Encoding

1508405313833  D/OkHttp  (12475): Expires: Thu, 19 Oct 2017 09:33:34 GMT

1508405313833  D/OkHttp  (12475): Cache-Control: max-age=300

1508405313833  D/OkHttp  (12475): Accept-Ranges: bytes

1508405313833  D/OkHttp  (12475): -- END HTTP

1508405313835  V/MixpanelAPI.Messages(12475): Flushing queue due to scheduled or forced flush (Thread 278062)

1508405313835  V/MixpanelAPI.Messages(12475): Average send frequency approximately 21 seconds. (Thread 278062)

1508405313836  V/MixpanelAPI.Message(12475): ConnectivityManager says we are online

1508405313843  V/MixpanelAPI.Message(12475): Attempting request to https://api.mixpanel.com/track?ip=1

1508405313844  I/System.out(12475): (HTTPLog)-Static: isSBSettingEnabled false

1508405313845  I/System.out(12475): (HTTPLog)-Static: isSBSettingEnabled false

1508405313929  V/MixpanelAPI.Messages(12475): Successfully posted to https://api.mixpanel.com/track?ip=1: 

1508405313929  V/MixpanelAPI.Messages(12475): [event:$ae_first_open,properties:mp_lib:android,$lib_version:5.2.1,$os:Android,$os_version:7.0,$manufacturer:samsung,$brand:samsung,$model:SM-G930F,$google_play_services:available,$screen_dpi:560,$screen_height:2560,$screen_width:1440,$app_version:3.2.-,$app_version_string:3.2.-,$app_release:20,$app_build_number:20,$has_nfc:true,$has_telephone:true,$carrier:csl.,$wifi:true,$bluetooth_version:ble,token:23357b9291bde449aa7c64ef85bdff47,time:1508405268,distinct_id:0ed01300-a93a-42e2-8535-864052862ae4,event:$ae_crashed,properties:mp_lib:android,$lib_version:5.2.1,$os:Android,$os_version:7.0,$manufacturer:samsung,$brand:samsung,$model:SM-G930F,$google_play_services:available,$screen_dpi:560,$screen_height:2560,$screen_width:1440,$app_version:3.2.-,$app_version_string:3.2.-,$app_release:20,$app_build_number:20,$has_nfc:true,$has_telephone:true,$carrier:csl.,$wifi:true,$bluetooth_version:ble,token:23357b9291bde449aa7c64ef85bdff47,time:1508405313,distinct_id:0ed01300-a93a-42e2-8535-864052862ae4,$ae_crashed_reason:io.reactivex.exceptions.OnErrorNotImplementedException: Null accessToken] (Thread 278062)

1508405313929  V/MixpanelAPI.Messages(12475): Response was status: 1, error: null (Thread 278062)

1508405313930  V/MixpanelAPI.Messages(12475): Not retrying this batch of events, deleting them from DB. (Thread 278062)


```

**Instabug Log:**
```

```

**User Steps:**
```
1508405268345 com.github.ayltai.newspaper.app.MainActivity was created.

1508405268787 com.github.ayltai.newspaper.app.MainActivity was started.

1508405268795 com.github.ayltai.newspaper.app.MainActivity was resumed.

1508405313227 In activity com.github.ayltai.newspaper.app.MainActivity: View of type android.view.View received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this because it is not valid for release build
