### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 400 

### ISSUE THREAD

**Issue by ayltai** [ayltai/Newspaper#122]
**Exception:** 	 io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 400 
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

Caused by: 
retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.Observable.subscribe(Observable.java:10910)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2779)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Number:** 	 13

**URL:** 	 https://insta.co/crashes/GuwesW9R

**Status:** 	 New

**Email:** 	 

**Reported At:** 	 2017-10-19 09:34:17 UTC

**Location:** 	 Central District, Hong Kong

**Device:** 	 samsung SM-G930F

**Memory:** 	 2562.0/3533.0 MB

**Storage:** 	 19.221/25.44 GB

**Connectivity:** 	 Carrier: csl., WiFi: 9GAG

**Battery:** 	 100, Charging through USB cable

**App Version:** 	 3.2.- (20)

**Duration:** 	 14

**User Data:** 	 

**Console Log:**
```
e.java:10910)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)

1508405657469  W/System.err(15549): 	at io.reactivex.Single.subscribe(Single.java:2779)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)

1508405657469  W/System.err(15549): 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)

1508405657469  W/System.err(15549): 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)

1508405657470  W/System.err(15549): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

1508405657470  W/System.err(15549): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)

1508405657470  W/System.err(15549): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)

1508405657470  W/System.err(15549): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

1508405657470  W/System.err(15549): 	at java.lang.Thread.run(Thread.java:762)

1508405657471  V/MixpanelAPI.PIdentity(15549): Loading Super Properties 

1508405657487  V/MixpanelAPI.Messages(15549): Queuing event for sending later (Thread 278108)

1508405657488  V/MixpanelAPI.Messages(15549):     event:$ae_crashed,properties:mp_lib:android,$lib_version:5.2.1,$os:Android,$os_version:7.0,$manufacturer:samsung,$brand:samsung,$model:SM-G930F,$google_play_services:available,$screen_dpi:560,$screen_height:2560,$screen_width:1440,$app_version:3.2.-,$app_version_string:3.2.-,$app_release:20,$app_build_number:20,$has_nfc:true,$has_telephone:true,$carrier:csl.,$wifi:true,$bluetooth_version:ble,token:23357b9291bde449aa7c64ef85bdff47,time:1508405657,distinct_id:0ed01300-a93a-42e2-8535-864052862ae4,$ae_crashed_reason:io.reactivex.exceptions.OnErrorNotImplementedException: HTTP 400  (Thread 278108)

1508405657515  V/MixpanelAPI.Messages(15549): Flushing queue due to scheduled or forced flush (Thread 278108)

1508405657516  V/MixpanelAPI.Message(15549): ConnectivityManager says we are online

1508405657523  V/MixpanelAPI.Message(15549): Attempting request to https://api.mixpanel.com/track?ip=1

1508405657524  I/System.out(15549): (HTTPLog)-Static: isSBSettingEnabled false

1508405657524  I/System.out(15549): (HTTPLog)-Static: isSBSettingEnabled false


```

**Instabug Log:**
```

```

**User Steps:**
```
1508405642604 com.github.ayltai.newspaper.app.MainActivity was created.

1508405643156 com.github.ayltai.newspaper.app.MainActivity was started.

1508405643161 com.github.ayltai.newspaper.app.MainActivity was resumed.

1508405651944 In activity com.github.ayltai.newspaper.app.MainActivity: View(description) of type android.support.v7.widget.AppCompatTextView received a click event


```

**Current View:** 	 com.github.ayltai.newspaper.app.MainActivity

**Locale:** 	 en_US

**Orientation:** 	 portrait

**Screen Size:** 	 1440x2560

**Density:** 	 xxhdpi

**Comment by ayltai** [comment]
Close this because it is not valid for release build
